### PR TITLE
Keyboard shortcuts and hotkeys

### PR DESCRIPTION
**Pull request by ajdor**
This PR adds support for hotkeys and keyboard shortcuts (as requested on Trello) to:
- open the extension menu (action menu) using **Ctrl+Alt+S** 
- generate a random email alias (which is copied to clipboard) using **Ctrl+Alt+X**
Other hotkeys can be added later as these may serve as an example.

These hotkeys can be edited using the browser's add-ons shortcuts settings:

image

Note: I have tested these changes on Firefox 80, can someone confirm that they work on other browsers too ?

### CODE REVIEW

**Comment by ngxson** [comment]
LGTM! I'll test on Chrome when I get home.

Just a side note: Some users may create alias note while they are in `about:*`, `moz-*` or `chrome-*` pages. In the future, we should have a function to detect that.

**Comment by nguyenkims** [comment]
@ajdor thanks for making the PR! 

I tried to test it but got this error when installing the extension in Chrome, do you have an idea?

image

Btw how does the shortcut adapt to Mac? On Mac the Ctrl is usually replaced by Cmd.

**Comment by ajdor** [comment]
@nguyenkims According to [mozilla's API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands/onCommand) (which is based on [chrome.commands API](https://developer.chrome.com/extensions/commands)), Ctrl is replaced by Command on Mac.
However, you can specify in the manifest what key combination should trigger the command on a each platform. For example:
```
"_execute_browser_action": {
  "suggested_key": {
    "windows": "Ctrl+Shift+Y",
    "mac": "Command+Shift+Y",
    "chromeos": "Ctrl+Shift+U",
    "linux": "Ctrl+Shift+J"
  }
}
```
or, if the hotkey is the same on all platform except mac:
```
"_execute_browser_action": {
  "suggested_key": {
    "default": "Ctrl+Shift+Y",
    "mac": "Command+Shift+Y"
  }
}
```
I initially used `default` alone since Ctrl is replaced by Command when the Ctrl key on mac is actually `MacCtrl`.

Regarding the issue, I got the same error after trying it on Chrome. it would seem that Chromium does not like using the Alt key in shortcuts. I have replaced it by Shift and it seems to be fixed.
I will commit the changes in this PR.

**Comment by nguyenkims** [comment]
I retested and everything is working perfectly, thanks!

**Pull request merged**
